# Below command is from: https://playwright.dev/docs/test-snapshots
# docker run --rm --network host -v $(pwd):/volumedir/ -w /volumedir/ -it mcr.microsoft.com/playwright:v1.30.0-focal /bin/bash 
# The command got translated to this docker compose for convenience

# Useful docker commands to use
# Spin up container with:     docker compose up -d
# Take down container with:   docker compose down | exit if container terminal is attached
# Use container's terminal via any of the following:
#   - vscode, new terminal:   docker attach pw-cont
#   - through docker desktop: requires running 'bash' so arrow keys/tabs/etc can be used

# Caveats:
# - PW runs must start with:  xvfb-run
# - Update snapshots with:    xvfb-run npx playwright test --update-snapshots

version: "3.8"                # docker compose version
services:
  playwright-container-service:
    container_name: pw-cont
    image: mcr.microsoft.com/playwright:v1.30.0-focal
    stdin_open: true          # -i
    tty: true                 # -t
    network_mode: host        # --network host
    volumes:                  # Ensures that updates in local/container are in sync
      - $PWD:/playwright/     # -v $(pwd):/volumedir/
    working_dir: /playwright  # -w /volumedir/
