# docker run --rm --network host -v $(pwd):/volumedir/ -w /volumedir/ -it mcr.microsoft.com/playwright:v1.30.0-focal /bin/bash 
# Above command is from: https://playwright.dev/docs/test-snapshots
# The command is translated to this docker compose for convenience

# Spin up container with:   docker compose up -d
# Use container terminal: in IDE via 'docker exec -it pw-cont /bin/bash' or through docker desktop
# Take down container with: docker compose down

version: "3.8"                # docker compose version
services:
  playwright-container-service:
    container_name: pw-cont
    image: mcr.microsoft.com/playwright:v1.30.0-focal
    tty: true                 # --it and /bin/bash equivalent
    network_mode: host        # --network host
    volumes:                  # Ensures that updates in local/container are in sync
      - $PWD:/playwright/     # -v $(pwd):/volumedir/
    working_dir: /playwright  # -w /volumedir/
