# There don't seem to be a way to cache playwright dependency
# Browser caching is not recommended since it only takes a few seconds, loading the cache sometimes takes longer

name: Run Playwright EtoE
on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

# permission for publishing on github pages
permissions:
  id-token: write
  pages: write
  contents: write

jobs:
  run-playwright-tests:
    timeout-minutes: 60
    # version must always match with docker image: https://hub.docker.com/_/microsoft-playwright
    runs-on: ubuntu-20.04

    steps:

    - name: Checkout the repo
      uses: actions/checkout@v3

    - name: Install Node 
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install Node dependencies
      run: npm ci

    # Install Playwirght Browsers
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
      env:
        DUMMY_TOKEN: ${{ secrets.DUMMY_TOKEN_GH_SECRET }}

    # xvfb-run allows headful browser testing
    - name: Run Playwright tests
      run: xvfb-run npx playwright test

    # Playwright report artifact, uncomment if needed
    # - name: Upload Playwright artifacts
    #   uses: actions/upload-artifact@v3
    #   if: success() || failure()
    #   with:
    #     name: playwright-report
    #     path: playwright-report/
    #     retention-days: 30

    # Allure tasks to upload report on GH pages
    - name: Get Allure history
      uses: actions/checkout@v3
      if: success() || failure()
      with:
        # The repo branch to checkout
        ref: allure-reports-history
        # Relative path under $GITHUB_WORKSPACE to place the repository branch that was checked out
        # $GITHUB_WORKSPACE is the default working directory on the runner for steps: /home/runner/work/repo_name/repo_name
        path: allure-reports-history

    - name: Generate Allure Report
      uses: simple-elf/allure-report-action@master
      if: success() || failure()
      id: allure-report
      with:
        allure_results: allure-test-results
        # The repo branch to use
        gh_pages: allure-reports-history
        allure_report: allure-report
        allure_history: allure-history
        keep_reports: 20

    - name: Deploy report to Github Pages
      if: success() || failure()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: allure-reports-history
        publish_dir: allure-history

    # Playwright HTML report upload to github pages
    # # Publish to github pages
    # - name: Setup Pages
    #   uses: actions/configure-pages@v2
    #   if: success() || failure()
    # - name: Upload artifact
    #   uses: actions/upload-pages-artifact@v1
    #   if: success() || failure()
    #   with:
    #     # Path of where the reports are saved
    #     path: playwright-report
    # - name: Deploy to GitHub Pages
    #   id: deployment
    #   uses: actions/deploy-pages@v1
    #   if: success() || failure()

    - name: GitHub Pages link
      run: echo "https://carlnoval.github.io/ts-playwright"
      if: success() || failure()
