# There don't seem to be a way to cache playwright dependency
# Browser caching is not recommended since it only takes a few seconds, loading the cache sometimes takes longer

name: Run Playwright EtoE
on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

# permission for publishing on github pages
permissions:
  id-token: write
  pages: write

jobs:
  run-playwright-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:

    - name: Checkout the repo
      uses: actions/checkout@v3

    - name: Install Node 
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install Node dependencies
      run: npm ci

    # Install Playwirght Browsers
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    # xvfb-run allows headful browser testing
    - name: Run Playwright tests
      run: xvfb-run npx playwright test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

    # Publish to github pages
    - name: Setup Pages
      uses: actions/configure-pages@v2
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        # Path of where the reports are saved
        path: playwright-report
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1

    - name: GitHub Pages link
      run: echo "https://carlnoval.github.io/ts-playwright"
