name: Run Playwright EtoE
on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

# permission for publishing on github pages
permissions:
  id-token: write
  pages: write

jobs:
  run-playwright-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: npm ci

    # Obtain project's playwright version
    - name: Store Playwright's Version
      run: |
        PLAYWRIGHT_VERSION=$(npm ls @playwright/test | grep @playwright | sed 's/.*@//')
        echo "Playwright's Version: $PLAYWRIGHT_VERSION"
        echo "PLAYWRIGHT_VERSION=$PLAYWRIGHT_VERSION" >> $GITHUB_ENV

    # Cache browsers using Playwright version as key
    - name: Cache Playwright Browsers for Playwright's Version
      id: cache-playwright-browsers
      uses: actions/cache@v3
      with:
        path: ~/.cache/ms-playwright
        key: playwright-browser-for-OS:${{ runner.os }}-PlaywrightVersion:${{ env.PLAYWRIGHT_VERSION }}

    # Install Playwirght Browsers if existing version don't match
    - name: Install Playwright Browsers
      if: steps.cache-playwright-browsers.outputs.cache-hit != 'true'
      run: npx playwright install --with-deps
    - name: Run Playwright tests

    # xvfb-run allows headful browser testing
      run: xvfb-run npx playwright test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

    # Publish to github pages
    - name: Setup Pages
      uses: actions/configure-pages@v2
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        # Upload entire repository
        path: playwright-report
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1

    - name: GitHub Pages link
      run: echo "https://carlnoval.github.io/ts-playwright"
